name: 'homebot_monitoring'
version: '1.0.0'
config-version: 2

profile: 'homebot_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"

models:
  homebot_monitoring:
    +materialized: table